apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - argo-deployments.yaml
  - argo-imagestreams.yaml
  - argo-management.yaml
  - argo-role.yaml
  - argo-ui-controller.yaml
  - argo-workflow-controller.yaml
  - postgresql.yaml
  - pgbouncer.yaml
  - postgresql-metrics-exporter.yaml
  - s3-storage.yaml
  - thoth-notification.yaml
patchesStrategicMerge:
  - configmaps.yaml
  - imagestreamtags.yaml
  - argo-workflows/send-message.yaml
  - argo-workflows/send-messages.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - ./secret-generator.yaml
# wf controller image patch
images:
  - name: argocli
    newName: image-registry.openshift-image-registry.svc:5000/thoth-test-core/argocli
    newTag: latest
  - name: workflow-controller
    newName: image-registry.openshift-image-registry.svc:5000/thoth-test-core/workflow-controller
    newTag: latest
patches:
  - patch: |-
      - op: replace
        path: /spec/templates/0/container/image
        value: image-registry.openshift-image-registry.svc:5000/thoth-test-core/messaging:latest
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      annotationSelector: "operation=messaging"
