---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: mi-scheduler
spec:
  output:
    to:
      kind: ImageStreamTag
      name: mi-scheduler:test
  runPolicy: Serial
  source:
    git:
      uri: https://github.com/thoth-station/mi-scheduler
      ref: master
    type: Git
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 512Mi
      cpu: 500m
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: s2i-thoth-ubi8-py36:latest
      env:
        - name: ENABLE_PIPENV
          value: "1"
        - name: UPGRADE_PIP_TO_LATEST
        - name: "THOTH_DRY_RUN"
          value: "1"
        - name: "THOTH_ADVISE"
          value: "0"
        - name: "THAMOS_VERBOSE"
          value: "1"
        - name: "THAMOS_DEBUG"
          value: "0"
        - name: "THAMOS_CONFIG_TEMPLATE"
          value: ".thoth.yaml"
        - name: "THAMOS_CONFIG_EXPAND_ENV"
          value: "1"
    type: Source
  triggers:
    - type: ImageChange
      imageChange: {}
