apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: graph-schema-update-job
resources:
  - ../../base
patchesStrategicMerge:
  - imagestreamtag.yaml
patchesJson6902:
  - path: put-into-infra-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: graph-schema-update-job
