apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deploymentconfig.yaml
  - imagestream.yaml
  - role_binding.yaml
  - role.yaml
  - route.yaml
  - service.yaml
  - serviceaccount.yaml
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: management-api
  app.kubernetes.io/managed-by: aicoe-thoth-devops-argocd
