---
kind: ConfigMap
apiVersion: v1
metadata:
  name: amun
data:
  amun-api-url: http://amun-api.thoth-amun-api-stage.svc
  deployment-name: ocp-stage
  infra-namespace: thoth-amun-inspection-stage
  inspection-namespace: thoth-amun-inspection-stage
  artifactRepository: |-
    archiveLogs: false
    s3:
      bucket: "{{workflow.parameters.ceph_bucket_name}}"
      endpoint: "{{workflow.parameters.ceph_host}}"
      accessKeySecret:
        name: argo-artifact-repository-secrets
        key: accessKey
      secretKeySecret:
        name: argo-artifact-repository-secrets
        key: secretKey
      keyFormat: "{{workflow.parameters.ceph_bucket_prefix}}/{{workflow.parameters.deployment_name}}/inspections/{{workflow.name}}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data"
  host: "https://s3.upshift.redhat.com/"
  endpoint: "https://s3.upshift.redhat.com/"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  pushgateway-host: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com
  pushgateway-port: "80"
  pushgateway-url: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com:80
