---
kind: ConfigMap
apiVersion: v1
metadata:
  name: amun
data:
  artifactRepository: |-
    archiveLogs: false
    s3:
      bucket: "{{workflow.parameters.ceph_bucket_name}}"
      endpoint: "{{workflow.parameters.ceph_host}}"
      accessKeySecret:
        name: argo-artifact-repository-secrets
        key: accessKey
      secretKeySecret:
        name: argo-artifact-repository-secrets
        key: secretKey
      keyFormat: "{{workflow.parameters.ceph_bucket_prefix}}/{{workflow.parameters.deployment_name}}/inspections/{{workflow.name}}"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: "k8sapi"
    parallelism: 4

    # metricsConfig controls the path and port for prometheus metrics
    metricsConfig:
      enabled: true
      path: /metrics
      port: 8080

    workflowDefaults:
      spec:
        parallelism: 10
