---
kind: ConfigMap
apiVersion: v1
metadata:
  name: slo-reporter
data:
  thanos-endpoint: "https://thanos-querier-openshift-monitoring.apps.balrog.aws.operate-first.cloud"
  smtp-server: "smtp.corp.redhat.com"
  sender-address: "aicoe-thoth@redhat.com"
  email-recipients: "aicoe-thoth@redhat.com"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: thoth
data:
  deployment-name: aws-prod
  amun-inspection-namespace: thoth-amun-inspection-prod
  amun-namespace: thoth-amun-api-prod
  backend-namespace: thoth-backend-prod
  middletier-namespace: thoth-middletier-prod
  frontend-namespace: thoth-frontend-prod
  infra-namespace: thoth-infra-prod
  storage-bucket-name: aws-prod
  logging-no-json: "0"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  public-bucket-name: DH-PLAYPEN
  bucket-name: "thoth-store"
  bucket-prefix: "data"
  host: "https://s3.amazonaws.com/"
  endpoint: "https://s3.amazonaws.com/"
  host-url: "https://thanos-querier-openshift-monitoring.apps.balrog.aws.operate-first.cloud"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  user-api-url: "user-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud:80"
  instance-metrics-exporter-infra: "metrics-exporter-thoth-infra-prod.apps.balrog.aws.operate-first.cloud:80"
  instance-metrics-management-api: "management-api-thoth-frontend-prod.apps.balrog.aws.operate-first.cloud:80"
  pushgateway-host: pushgateway-thoth-infra-prod.apps.balrog.aws.operate-first.cloud
  pushgateway-port: "80"
  pushgateway-url: pushgateway-thoth-infra-prod.apps.balrog.aws.operate-first.cloud:80
  instance-workflow-controller-metrics-backend: "workflow-controller-metrics-thoth-backend-prod.apps.balrog.aws.operate-first.cloud:80"
  instance-workflow-controller-metrics-middletier: "workflow-controller-metrics-thoth-middletier-prod.apps.balrog.aws.operate-first.cloud:80"
  instance-workflow-controller-metrics-amun-inspection: "workflow-controller-metrics-thoth-amun-inspection-prod.apps.balrog.aws.operate-first.cloud:80"
