---
kind: ConfigMap
apiVersion: v1
metadata:
  name: adviser
data:
  validate-prescription-schema: "1"
  validate-unit-configuration-schema: "1"
  blocked-units: "SecurityIndicatorStep,ThothS2IAbiCompatibilitySieve"
  search-url: "https://thoth-station.ninja/search-stage/{document_id}/summary"
