apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cronjob.yaml
  - deployment-config.yaml
  - imagestream.yaml
  - route.yaml
  - service.yaml
  - serviceaccount.yaml
commonLabels:
  app: thoth
  component: package-update
