apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: sefkhet-abwy
  app.kubernetes.io/component: webhook-receiver
  app.kubernetes.io/managed-by: aicoe-thoth-devops
resources:
  - deploymentconfig.yaml
  - imagestream.yaml
  - service.yaml
  - route.yaml
