apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: metrics-exporter
  app.kubernetes.io/managed-by: aicoe-thoth-devops-argocd
resources:
  - configmap.yaml
  - deploymentconfig.yaml
  - imagestream.yaml
  - role.yaml
  - rolebinding.yaml
  - route.yaml
  - service.yaml
  - serviceaccount.yaml
