apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - imagestream.yaml
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: kebechet
  app.kubernetes.io/managed-by: aicoe-thoth-devops-argocd
