apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - imagestream.yaml
  - argo-workflows/kebechet.yaml
  - openshift-templates/kebechet.yaml
  - argo-workflows/kebechet-run-url.yaml
  - openshift-templates/kebechet-run-url.yaml
  - argo-workflows/kebechet-administrator.yaml
  - openshift-templates/kebechet-administrator.yaml
  - argo-workflows/update_keb_installation.yaml
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: kebechet
  app.kubernetes.io/managed-by: aicoe-thoth-devops
