---
kind: ConfigMap
apiVersion: v1
metadata:
  name: thoth
data:
  applicationName: "thoth"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: solvers
data:
  solvers: |
    solver-rhel-8-py36
    solver-fedora-31-py38
    solver-fedora-31-py37
    solver-fedora-32-py37
    solver-fedora-32-py38
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
data:
  kafka-client-id: "thoth-messaging"
  kafka-ssl-auth: "1"
  kafka-topic-retention-time: "8640"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
---
# Change webhook and split into test, stage, prod once available
kind: ConfigMap
apiVersion: v1
metadata:
  name: qeb-hwt-workflow
data:
  webhook-callback-url: "http://qeb-hwt-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com"
