apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - imagestreamtag.yaml
  - serviceaccount.yaml
  - role.yaml
  - role_binding.yaml
  - deploymentconfig.yaml
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: build-watcher
  app.kubernetes.io/managed-by: aicoe-thoth-devops
