---
kind: ConfigMap
apiVersion: v1
metadata:
  name: sefkhet-abwy
data:
  subdomain: sefkhet-abwy
  webhook-callback-url: "http://sefkhet-abwy-webhook-receiver-thoth-bots-prod.apps.zero.massopen.cloud"
