apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base
  - argo-role.yaml
  - buildconfig.yaml
  - configmaps.yaml
  - role_binding.yaml
  - secrets.yaml
patchesStrategicMerge:
# generators:
#   - ./secret-generator.yaml
patchesJson6902:
  - path: put-into-inspection-namespace.yaml
    target:
      group: image.openshift.io
      version: v1
      kind: ImageStream
      name: kubectl
  - path: put-into-inspection-namespace.yaml
    target:
      group: image.openshift.io
      version: v1
      kind: ImageStream
      name: amun-inspect-hwinfo
  - path: put-into-inspection-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: amun-inspection-workflow-with-cpu
  - path: put-into-inspection-namespace.yaml
    target:
      group: template.openshift.io
      version: v1
      kind: Template
      name: amun-inspection-workflow
  - path: put-into-inspection-namespace.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: inspection-build-with-cpu-template
  - path: put-into-inspection-namespace.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: inspection-build-template
  - path: put-into-inspection-namespace.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: inspection-run-with-cpu-template
  - path: put-into-inspection-namespace.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: WorkflowTemplate
      name: inspection-run-template
  - path: put-into-inspection-namespace.yaml
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: amun-api-workflow
  - path: put-into-inspection-namespace.yaml
    target:
      group: ""
      version: v1
      kind: ServiceAccount
      name: amun-prepare-workflow
  - path: put-into-inspection-namespace.yaml
    target:
      group: "rbac.authorization.k8s.io"
      version: v1
      kind: Role
      name: amun-api
  - path: put-into-inspection-namespace.yaml
    target:
      group: "rbac.authorization.k8s.io"
      version: v1
      kind: Role
      name: amun-api-workflow
  - path: put-into-inspection-namespace.yaml
    target:
      group: "rbac.authorization.k8s.io"
      version: v1
      kind: Role
      name: amun-prepare-workflow
