apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: package-extract
  app.kubernetes.io/managed-by: aicoe-thoth-devops
resources:
  - openshift-templates/build-analysis.yaml
  - openshift-templates/package-extract.yaml
  - argo-workflows/package-extract.yaml
  - imagestream.yaml
