apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/version: "0.6.0"
resources:
  - ../../base
  - thoth-notification.yaml
patchesStrategicMerge:
  - imagestreamtag.yaml
patchesJson6902:
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-success-
      namespace: thoth-infra-stage
  - path: job-generate-name.yaml
    target:
      group: batch
      version: v1
      kind: Job
      name: chat-notification-fail-
      namespace: thoth-infra-stage
