apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deploymentconfig.yaml
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: investigator
  app.kubernetes.io/managed-by: aicoe-thoth-devops-argocd
