---
kind: ConfigMap
apiVersion: v1
metadata:
  name: amun
data:
  amun-api-url: http://amun-api.thoth-amun-api-prod.svc
  deployment-name: smaug-prod
  infra-namespace: thoth-amun-inspection-prod
  inspection-namespace: thoth-amun-inspection-prod
  logging-no-json: "0"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data"
  host: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"
  endpoint: "http://rook-ceph-rgw-ocs-storagecluster-cephobjectstore.openshift-storage.svc.cluster.local"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  pushgateway-host: prometheus-portal-thoth-infra-prod.apps.smaug.na.operate-first.cloud
  pushgateway-port: "80"
  pushgateway-url: prometheus-portal-thoth-infra-prod.apps.smaug.na.operate-first.cloud:80
