apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - deploymentconfig.yaml
  - imagestream.yaml
  - route.yaml
  - service.yaml
commonLabels:
  app.kubernetes.io/name: thoth
  app.kubernetes.io/component: advise-reporter
  app.kubernetes.io/managed-by: aicoe-thoth-devops-argocd
