---
kind: ConfigMap
apiVersion: v1
metadata:
  name: thoth
data:
  applicationVersion: 0.7.0
  deployment-name: ocp-stage
  amun-api-url: "UNSET"
  amun-inspection-namespace: thoth-amun-inspection-stage
  amun-namespace: thoth-amun-api-stage
  backend-namespace: aicoe-infra-prod
  middletier-namespace: thoth-middletier-stage
  frontend-namespace: thoth-frontend-stage
  infra-namespace: thoth-infra-stage
  solvers: |
    solver-rhel-8-py36
    solver-fedora-31-py38
    solver-fedora-31-py37
    solver-fedora-32-py37
    solver-fedora-32-py38
  package-releases-only-if-package-seen: "1"
  postgresql-host: pgbouncer.thoth-graph-stage.svc
  rsyslog-host: ""
  rsyslog-port: ""
  storage-bucket-name: ocp-prod-stage
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data"
  host: "https://s3.upshift.redhat.com/"
  endpoint: "https://s3.upshift.redhat.com/"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
data:
  kafka-bootstrap-servers: "thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth12.lab.upshift.rdu2.redhat.com:443"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  host-url: "https://prometheus-dh-prod-monitoring.cloud.datahub.psi.redhat.com"
  instance-metrics-exporter-frontend: "metrics-exporter-thoth-frontend-stage.cloud.paas.psi.redhat.com:80"
  pushgateway-host: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com
  pushgateway-port: "80"
  pushgateway-url: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com:80
