---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: qeb-hwt-webhook-receiver
spec:
  test: false
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    deploymentconfig: qeb-hwt-webhook-receiver
    app.kubernetes.io/name: qeb-hwt
    app.kubernetes.io/component: webhook-receiver
    app.kubernetes.io/managed-by: aicoe-thoth-devops
  template:
    metadata:
      labels:
        deploymentconfig: qeb-hwt-webhook-receiver
        app.kubernetes.io/name: qeb-hwt
        app.kubernetes.io/component: webhook-receiver
        app.kubernetes.io/managed-by: aicoe-thoth-devops
    spec:
      containers:
        - name: webhook-receiver
          image: qeb-hwt-webhook-receiver
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: ENV
              value: dev
            - name: PYTHONPATH
              value: .
            - name: THOTH_DEPLOYMENT_NAME
              value: aicoe-prod-bots
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  key: sentry-dsn
                  name: qeb-hwt
          envFrom:
            - prefix: GITHUB_
              secretRef:
                name: qeb-hwt-github-app
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
