---
kind: ConfigMap
apiVersion: v1
metadata:
  name: thoth
data:
  applicationVersion: 0.7.0
  deployment-name: ocp-stage
  amun-api-url: "http://amun-api-thoth-amun-api-stage.apps.ocp.prod.psi.redhat.com"
  amun-inspection-namespace: thoth-amun-inspection-stage
  amun-namespace: thoth-amun-api-stage
  backend-namespace: thoth-backend-stage
  middletier-namespace: thoth-middletier-stage
  frontend-namespace: thoth-frontend-stage
  infra-namespace: thoth-infra-stage
  solvers: |
    solver-rhel-8-py36
  package-releases-only-if-package-seen: "1"
  postgresql-host: pgbouncer.thoth-graph-stage.svc
  rsyslog-host: ""
  rsyslog-port: ""
  storage-bucket-name: ocp-stage
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data"
  public-bucket-name: DH-PLAYPEN
  host: "https://s3.upshift.redhat.com/"
  endpoint: "https://s3.upshift.redhat.com/"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
data:
  kafka-protocol: "SSL"
  kafka-bootstrap-servers: "thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth02.lab.upshift.rdu2.redhat.com:443"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  host-url: "https://prometheus-dh-prod-monitoring.cloud.datahub.psi.redhat.com"
  user-api-url: "user-api-thoth-frontend-stage.apps.ocp.prod.psi.redhat.com:80"
  instance-metrics-exporter-infra: "metrics-exporter-thoth-infra-stage.apps.ocp.prod.psi.redhat.com:80"
  instance-metrics-management-api: "management-api-thoth-frontend-stage.apps.ocp.prod.psi.redhat.com:80"
  pushgateway-host: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com
  pushgateway-port: "80"
  pushgateway-url: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com:80
  instance-workflow-controller-metrics-backend: "workflow-controller-metrics-thoth-backend-stage.apps.ocp.prod.psi.redhat.com:80"
  instance-workflow-controller-metrics-middletier: "workflow-controller-metrics-thoth-middletier-stage.apps.ocp.prod.psi.redhat.com:80"
  instance-workflow-controller-metrics-amun-inspection: "workflow-controller-metrics-thoth-amun-inspection-stage.apps.ocp.prod.psi.redhat.com:80"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: qeb-hwt-workflow
data:
  webhook-callback-url: "http://qeb-hwt-webhook-receiver-aicoe-prod-bots.apps.ocp.prod.psi.redhat.com"
