---
kind: ConfigMap
apiVersion: v1
metadata:
  name: thoth
data:
  applicationVersion: 0.6.0-dev
  deploymentName: thoth-test-core
  postgresql-host: postgresql.thoth-test-core.svc
  backend-namespace: thoth-test-core
  middletier-namespace: thoth-test-core
  frontend-namespace: thoth-test-core
  infra-namespace: thoth-test-core
  solvers: |
    solver-rhel-8-py36
    solver-fedora-31-py38
    solver-fedora-31-py37
    solver-fedora-32-py37
    solver-fedora-32-py38
  analyzer-cleanup-time: 1d
  middletier-pod-cpu-limit: "0.5"
  middletier-pod-memory-limit: "0.5Gi"
  package-releases-only-if-package-seen: "1"
  sync-observations: "0"
  rsyslog-host: ""
  rsyslog-port: ""
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data/thoth-test-core-thoth01"
  host: "https://s3.upshift.redhat.com/"
  endpoint: "https://s3.upshift.redhat.com/"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
data:
  kafka-bootstrap-servers: "thoth-kafka-bootstrap-thoth-infra-stage.apps.thoth01.lab.upshift.rdu2.redhat.com:443"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: workflow-controller-configmap
data:
  config: |
    containerRuntimeExecutor: "k8sapi"
    namespace: "thoth-test-core"
    parallelism: 10

    # metricsConfig controls the path and port for prometheus metrics
    metricsConfig:
      enabled: true
      path: /metrics
      port: 8080

    artifactRepository:
      archiveLogs: False

      s3:
        bucket: "DH-DEV-DATA"
        keyPrefix: "data/thoth/thoth-test-core/argo/artifacts/"
        endpoint: "s3.upshift.redhat.com"
        insecure: true
        accessKeySecret:
          name: argo-artifact-repository-secrets
          key: accessKey
        secretKeySecret:
          name: argo-artifact-repository-secrets
          key: secretKey
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  host-url: "https://prometheus-dh-prod-monitoring.cloud.datahub.psi.redhat.com"
  instance-metrics-exporter-frontend: "metrics-exporter-thoth-test-core.cloud.paas.psi.redhat.com:80"
  instance-workflow-metrics-amun-inspection: "workflow-controller-metrics-thoth-test-core.cloud.paas.psi.redhat.com:80"
  instance-workflow-metrics-backend: "workflow-controller-metrics-thoth-test-core.cloud.paas.psi.redhat.com:80"
  instance-workflow-metrics-middletier: "workflow-controller-metrics-thoth-test-core.cloud.paas.psi.redhat.com:80"
  pushgateway-host: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com
  pushgateway-port: "80"
  pushgateway-url: pushgateway-dh-prod-monitoring.cloud.datahub.psi.redhat.com:80
