---
kind: ConfigMap
apiVersion: v1
metadata:
  name: amun
data:
  amun-api-url: http://amun-api.thoth-amun-api-prod.svc
  deployment-name: zero-prod
  infra-namespace: thoth-amun-inspection-prod
  inspection-namespace: thoth-amun-inspection-prod
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data"
  host: "http://s3.openshift-storage.svc.cluster.local"
  endpoint: "http://s3.openshift-storage.svc.cluster.local"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  pushgateway-host: prometheus-portal-thoth-infra-prod.apps.zero.massopen.cloud
  pushgateway-port: "80"
  pushgateway-url: prometheus-portal-thoth-infra-prod.apps.zero.massopen.cloud:80
