plank:
  report_templates:
    "*": "[Full PR test history](https://prow.operate-first.cloud/pr-history?org={{.Spec.Refs.Org}}&repo={{.Spec.Refs.Repo}}&pr={{with index .Spec.Refs.Pulls 0}}{{.Number}}{{end}}). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3A{{with index .Spec.Refs.Pulls 0}}{{.Author}}{{end}}). Please help us and [open an issue](https://github.com/{{.Spec.Refs.Org}}/{{.Spec.Refs.Repo}}/issues?q=is:issue+is:open) when you hit one in your PR."
  job_url_prefix_config:
    "*": https://prow.operate-first.cloud/view/
  default_decoration_configs:
    "*":
      gcs_configuration:
        bucket: s3://ci-prow-artifacts--36f9ca3b-f5af-4432-bef8-af42508b403e/prow-logs
        path_strategy: explicit
      s3_credentials_secret: s3-credentials
      utility_images:
        clonerefs: gcr.io/k8s-prow/clonerefs:v20210319-be35a198b9
        entrypoint: gcr.io/k8s-prow/entrypoint:v20210319-be35a198b9
        initupload: gcr.io/k8s-prow/initupload:v20210319-be35a198b9
        sidecar: gcr.io/k8s-prow/sidecar:v20210319-be35a198b9

prowjob_namespace: opf-ci-prow
pod_namespace: opf-ci-prow

in_repo_config:
  enabled:
    thoth-station: true
    operate-first: true
    aicoe-aiops: true

  allowed_clusters:
    "thoth-station": ["api-zero-massopen-cloud:6443"]

branch-protection:
  allow_disabled_policies: true
  orgs:
    thoth-station:
      protect: true
      allow_force_pushes: false
      required_status_checks:
        contexts:
          - aicoe-ci/prow/pre-commit
      exclude:
        - "^revert-"
        - "^kebechet-"
        - "^dependabot/"
      restrictions:
        users: []
        teams:
          - sourceops
        required_pull_request_reviews:
          dismiss_stale_reviews: false
          required_approving_review_count: 1
      repos:
        tensorflow:
          protect: false
        contra-env-infra:
          protect: false
        statusfy:
          protect: false
        statusfy-ops:
          protect: false
        website-tooling:
          protect: false
        cuda:
          protect: false
        stub-api:
          protect: false
        nvidia-usage-dashboard:
          protect: false
        template-project:
          protect: false
        pipelines-catalog:
          protect: false
        bz1816214-example:
          protect: false

deck:
  spyglass:
    size_limit: 100000000 # 100MB
    # gcs_browser_prefix: https://gcsweb.k8s.io/gcs/
    # testgrid_config: gs://k8s-testgrid/config
    # testgrid_root: https://testgrid.k8s.io/
    lenses:
      - lens:
          name: metadata
        required_files:
          - ^(?:started|finished)\.json$
        optional_files:
          - ^(?:podinfo|prowjob)\.json$
      - lens:
          name: buildlog
          config:
            highlight_regexes:
              - timed out
              - "ERROR:"
              - (FAIL|Failure \[)\b
              - panic\b
              - ^E\d{4} \d\d:\d\d:\d\d\.\d\d\d]
              - "^INFO: Analyzed \\d+ targets"
        required_files:
          - ^.*build-log\.txt$
      - lens:
          name: podinfo
        required_files:
          - ^podinfo\.json$
  tide_update_period: 1s

tide:
  pr_status_base_urls:
    "*": https://prow.operate-first.cloud/pr

  merge_method:
    aicoe-aiops: squash
    AICoE: squash
    operate-first: squash
    thoth-station: squash

  queries:
    - orgs:
        - aicoe-aiops
        - operate-first
        - thoth-station
      excludedRepos:
        - thoth-station/dgraph-thoth-config
        - thoth-station/workload-operator
        - thoth-station/tensorflow
        - thoth-station/contra-env-infra
        - thoth-station/ansible-role-core-imagestreams
        - thoth-station/ansible-role-core-templates
        - thoth-station/ansible-role-core-cronjob
        - thoth-station/ansible-role-metrics-exporter
        - thoth-station/ansible-role-cronjob
        - thoth-station/ansible-role-argo-workflows
        - thoth-station/ansible-role-postgresql
        - thoth-station/ansible-role-kebechet
        - thoth-station/ansible-role-postgresql-metrics-exporter
        - thoth-station/statusfy
        - thoth-station/statusfy-ops
        - thoth-station/website-tooling
        - thoth-station/cuda
        - thoth-station/stub-api
        - thoth-station/nvidia-usage-dashboard
        - thoth-station/pipelines-catalog
        - thoth-station/bz1816214-example
      labels:
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase
    - repos:
        - AICoE/aicoe-cd
        - AICoE/aicoe-ci
        - AICoE/aicoe-sre
        - AICoE/idh-manifests
        - AICoE/internal-data-hub
        - AICoE/prometheus-anomaly-detector
        - AICoE/prometheus-api-client-python
        - AICoE/s2i-custom-notebook
        - AICoE/sefkhet-abwy
      labels:
        - approved
      missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/invalid-owners-file
        - do-not-merge/work-in-progress
        - needs-rebase

  blocker_label: tide/merge-blocker
  squash_label: tide/merge-method-squash
  rebase_label: tide/merge-method-rebase
  merge_label: tide/merge-method-merge

  context_options:
    from-branch-protection: true
    skip-unknown-contexts: true
    orgs:
      AICoE:
        repos:
          s2i-custom-notebook:
            required-contexts:
              - aicoe-ci/pre-commit-check
              - aicoe-ci/build-check
          prometheus-api-client-python:
            required-contexts:
              - aicoe-ci/pre-commit-check
              - aicoe-ci/pytest-check
          sefkhet-abwy:
            required-contexts:
              - aicoe-ci/pre-commit-check
              - aicoe-ci/build-check
          pricingnbs:
            required-contexts:
              - aicoe-ci/pre-commit-check
              - aicoe-ci/build-check
      thoth-station:
        repos:
          adviser:
            required-contexts:
              - aicoe-ci/build-check
          amun-api:
            required-contexts:
              - aicoe-ci/pre-commit-check
              - aicoe-ci/build-check
          buildlog-parser:
            required-contexts:
              - aicoe-ci/build-check
          datasets:
            required-contexts:
              - aicoe-ci/build-check
          init-job:
            required-contexts:
              - aicoe-ci/build-check
          invectio:
            required-contexts:
              - aicoe-ci/pytest-check
          integration-tests:
            required-contexts:
              - aicoe-ci/build-check
          kebechet:
            required-contexts:
              - aicoe-ci/build-check
          management-api:
            required-contexts:
              - aicoe-ci/build-check
          user-api:
            required-contexts:
              - aicoe-ci/build-check
          package-extract:
            required-contexts:
              - aicoe-ci/build-check
          si-aggregator:
            required-contexts:
              - aicoe-ci/build-check
          si-bandit:
            required-contexts:
              - aicoe-ci/build-check
          si-cloc:
            required-contexts:
              - aicoe-ci/build-check
          solver:
            required-contexts:
              - aicoe-ci/pytest-check
          investigator:
            required-contexts:
              - aicoe-ci/build-check
          workflow-helpers:
            required-contexts:
              - aicoe-ci/build-check
          report-processing:
            required-contexts:
              - aicoe-ci/build-check
          elyra-aidevsecops-tutorial:
            required-contexts:
              - aicoe-ci/build-check

periodics:
  - name: integration-tests-moc
    interval: 8h
    decorate: true
    spec:
      containers:
        - image: quay.io/thoth-station/integration-tests:v0.8.0
          imagePullPolicy: Always
          command:
            - python3
            - app.py
          env:
            - name: THOTH_DEPLOYMENT_NAME
              value: zero-prod
            - name: MAIL_REPORT
              value: "0"
            - name: THOTH_USER_API_HOST
              value: api.moc.thoth-station.ninja
            - name: THOTH_MANAGEMENT_API_HOST
              value: management.moc.thoth-station.ninja
            - name: THOTH_AMUN_API_HOST
              value: amun.moc.thoth-station.ninja
            - name: THOTH_MANAGEMENT_API_SECRET
              value: ""
    annotations:
      description: Periodic e2e tests against MOC deployment

presubmits:
  thoth-station/s2i-generic-data-science-notebook:
    - name: pre-commit
      decorate: true
      skip_report: false
      always_run: true
      context: aicoe-ci/prow/pre-commit
      spec:
        containers:
          - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.5
            command:
              - "pre-commit"
              - "run"
              - "--all-files"
            resources:
              requests:
                memory: "2Gi"
                cpu: "2"

  thoth-station/integration-tests:
    - name: pre-commit
      decorate: true
      skip_report: false
      always_run: true
      context: aicoe-ci/prow/pre-commit
      spec:
        containers:
          - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.5
            command:
              - "pre-commit"
              - "run"
              - "--all-files"
            resources:
              requests:
                memory: "2Gi"
                cpu: "2"
    - name: integration-tests-moc
      decorate: true
      skip_report: false
      always_run: false
      context: aicoe-ci/prow/integration-tests
      spec:
        containers:
          - image: quay.io/thoth-station/integration-tests:pr-136
            imagePullPolicy: Always
            command:
              - python3
              - app.py
            env:
              - name: THOTH_DEPLOYMENT_NAME
                value: zero-prod
              - name: GENERATE_REPORT
                value: "1"
              - name: MAIL_REPORT
                value: "0"
              - name: THOTH_USER_API_HOST
                value: api.moc.thoth-station.ninja
              - name: THOTH_MANAGEMENT_API_HOST
                value: management.moc.thoth-station.ninja
              - name: THOTH_AMUN_API_HOST
                value: amun.moc.thoth-station.ninja
              - name: THOTH_MANAGEMENT_API_SECRET
                value: ""

  AICoE/pricingnbs:
    - name: pre-commit
      decorate: true
      skip_report: false
      always_run: true
      context: aicoe-ci/prow/pre-commit
      spec:
        containers:
          - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.5
            command:
              - "pre-commit"
              - "run"
              - "--all-files"
            resources:
              requests:
                memory: "2Gi"
                cpu: "2"
