apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - roles.yaml
  - rolebindings.yaml
  - s3-bucket-claim.yaml
patchesStrategicMerge:
  - imagestreamtags.yaml
configMapGenerator:
  - name: config
    files:
      - config.yaml
  - name: plugins
    files:
      - plugins.yaml
generatorOptions:
  disableNameSuffixHash: true
generators:
  - secret-generator.yaml
