---
kind: ConfigMap
apiVersion: v1
metadata:
  name: thoth
data:
  applicationVersion: 0.7.0
  deployment-name: moc-prod
  amun-api-url: "https://amun.moc.thoth-station.ninja"
  amun-inspection-namespace: thoth-amun-inspection-prod
  amun-namespace: thoth-amun-api-prod
  backend-namespace: thoth-backend-prod
  middletier-namespace: thoth-middletier-prod
  frontend-namespace: thoth-frontend-prod
  infra-namespace: thoth-infra-prod
  solvers: |
    solver-rhel-8-py36
    solver-fedora-31-py38
    solver-fedora-31-py37
    solver-fedora-32-py37
    solver-fedora-32-py38
  package-releases-only-if-package-seen: "1"
  postgresql-host: pgbouncer.thoth-graph-prod.svc
  rsyslog-host: ""
  rsyslog-port: ""
  storage-bucket-name: moc-prod
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: ceph
data:
  bucket-name: "thoth"
  bucket-prefix: "data"
  host: "https://kzn-swift.massopen.cloud/"
  endpoint: "https://kzn-swift.massopen.cloud/"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: kafka
data:
  kafka-bootstrap-servers: ""
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus
data:
  host-url: "https://prometheus-dh-prod-monitoring.k-apps.osh.massopen.cloud/"
  instance-metrics-exporter-infra: "metrics-exporter-thoth-infra-prod.k-apps.osh.massopen.cloud:80"
  pushgateway-host: pushgateway-opendatahub.k-apps.osh.massopen.cloud
  pushgateway-port: "80"
  pushgateway-url: pushgateway-opendatahub.k-apps.osh.massopen.cloud:80
